# Generated by Django 6.0.1 on 2026-01-22 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(max_length=30)),
                ('siret', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_description', models.TextField()),
                ('price_ht', models.FloatField()),
                ('tax', models.FloatField()),
                ('price_it', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=30)),
                ('siret', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('id_product', models.IntegerField()),
                ('description_products', models.TextField()),
                ('price_ht', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.contact')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceOrderLine',
            fields=[
                ('invoice_order_line_id', models.AutoField(primary_key=True, serialize=False)),
                ('price_ht', models.FloatField()),
                ('tax', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.contact')),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.invoice')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.product')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('sales_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.contact')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('sales_order_line_id', models.AutoField(primary_key=True, serialize=False)),
                ('price_ht', models.FloatField()),
                ('tax', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('genre', models.CharField(max_length=50)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.contact')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.product')),
                ('sales_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.salesorder')),
            ],
        ),
    ]
