# Generated by Django 6.0.1 on 2026-01-22 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceorderline',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='invoiceorderline',
            name='contact_id',
        ),
        migrations.RemoveField(
            model_name='invoiceorderline',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='salesorderline',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='contact_id',
        ),
        migrations.RemoveField(
            model_name='salesorderline',
            name='sales_order_id',
        ),
        migrations.RemoveField(
            model_name='salesorderline',
            name='contact_id',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceOrderLine',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='SalesOrder',
        ),
        migrations.DeleteModel(
            name='SalesOrderLine',
        ),
    ]
