# Generated by Django 6.0.1 on 2026-01-22 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0002_remove_invoiceorderline_invoice_id_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=30)),
                ('siret', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('id_product', models.IntegerField()),
                ('description_products', models.TextField()),
                ('price_ht', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.contact')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceOrderLine',
            fields=[
                ('invoice_order_line_id', models.AutoField(primary_key=True, serialize=False)),
                ('price_ht', models.FloatField()),
                ('tax', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.contact')),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.invoice')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product')),
            ],
        ),
    ]
