# Generated by Django 6.0.1 on 2026-01-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceorderline',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
