# Generated by Django 6.0.1 on 2026-02-10 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_invoiceorderline_status'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceorderline',
            name='price_tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceorderline',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='invoiceorderline',
            name='status',
            field=models.CharField(choices=[('MULTIPLE', 'Paiement en plusieurs fois'), ('PAID', 'Réglé'), ('WAITING', 'En attente'), ('CANCELLED', 'Annulée')], default='WAITING', max_length=20),
        ),
    ]
