# Generated by Django 6.0.1 on 2026-02-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_invoiceorderline_price_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceorderline',
            name='price_tax',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
