# Generated by Django 6.0.1 on 2026-02-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_alter_invoiceorderline_price_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceorderline',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('réglé', 'réglé')], default='En attente', max_length=20),
        ),
    ]
