# Generated by Django 6.0.1 on 2026-02-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_alter_invoiceorderline_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceorderline',
            name='status',
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('réglé', 'Réglé')], default='En attente', max_length=20),
        ),
    ]
