# Generated by Django 6.0.1 on 2026-01-22 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0002_remove_invoiceorderline_invoice_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_description', models.TextField()),
                ('price_ht', models.FloatField()),
                ('tax', models.FloatField()),
                ('price_it', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('sales_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.contact')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('sales_order_line_id', models.AutoField(primary_key=True, serialize=False)),
                ('price_ht', models.FloatField()),
                ('tax', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('genre', models.CharField(max_length=50)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.contact')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product')),
                ('sales_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesorder')),
            ],
        ),
    ]
