# Generated by Django 6.0.1 on 2026-02-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_salesorderline_product_id_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='type',
            field=models.CharField(choices=[('Devis', 'Devis'), ('Commande', 'Commande')], default='Devis', max_length=30),
        ),
    ]
