# Generated by Django 6.0.1 on 2026-02-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_salesorder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterModelTable(
            name='salesorder',
            table='sales_order',
        ),
        migrations.AlterModelTable(
            name='salesorderline',
            table='sales_order_line',
        ),
    ]
