# Generated by Django 6.0.1 on 2026-02-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesorder_created_at_salesorder_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderline',
            name='price_it',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='price_ht',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
