# Generated by Django 6.0.1 on 2026-02-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesorderline_price_it_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='public_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='public_hash_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='signed_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('Envoyé', 'Envoyé'), ('Signé', 'Signé'), ('Commandé', 'Commandé')], default='Envoyé', max_length=30),
        ),
    ]
