# Generated by Django 6.0.1 on 2026-02-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_description', models.TextField(max_length=40, unique=True)),
                ('price_ht', models.FloatField()),
                ('tax', models.FloatField()),
                ('price_it', models.FloatField()),
            ],
        ),
    ]
