# Generated by Django 6.0.1 on 2026-02-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('achat', 'achat'), ('vente', 'vente'), ('achat/vente', 'achat/vente')], default='achat/vente', max_length=20),
        ),
    ]
