# Generated by Django 6.0.1 on 2026-02-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_ht',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_it',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
